project:
  type: website

website:
  title: "Vivek's Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vphalak
      - icon: twitter
        href: https://twitter.com/vphalak
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


